### ISSUE TITLE
[BUG] Tablet is not showing anything

### ISSUE THREAD

**Issue by galfar-coder** [NikoGameing/Weather2-Additions#1]
So, the issue, The tablet is not showing anything. It may be because I have some rendering mods installed (Iris, Embedium), and also first person model.

![image](https://github.com/user-attachments/assets/d33ebf98-0f09-4879-b546-092295d2ba31)

If there is more info needed, I am able to provide it :)

* MC Version: 1.20.1

**Comment by galfar-coder** [comment]
<details>

<summary>My installed mods</summary>

- AppleSkin
- Architectury
- Balm
- Better Animations Collection
- Biomes O' Plenty
- Botarium
- Cave Dust
- Cloth Config v10 API
- Comforts
- CoroUtil
- CraterLib
- Create
- Create Big Cannons
- Create Crafts & Additions
- Create Deco
- Create Enchantment Industry
- Create Goggles
- Create Slice & Dice
- Create: Bells & Whistles
- Create: Copycats\+
- Create: New Age
- Create: Steam 'n' Rails
- Create: Structures
- Curios API
- Dynamic Crosshair
- Dynamic Lights
- Embeddium
- EntityCulling
- Ferrite Core
- Figura
- FirstPerson
- ForgeEndertech
- Framework
- GlitchCore
- Jade
- Kotlin for Forge
- Mouse Tweaks
- NotEnoughAnimations
- Oculus
- Oculus Flywheel Compat
- Pollution of the Realms
- Polymorph
- Puzzles Lib
- REI Plugin Compatibilities
- Roughly Enough Config Screens
- Roughly Enough Items \(REI\)
- Roughly Enough Professions
- Scorched Guns
- Simple RPC
- Sound Physics Remastered
- Tectonic
- TerraBlender
- Visual Workbench
- Waystones
- Weather2
- Weather2 Additions
- Zombies\+
</details>

**Comment by NikoGameing** [comment]
fixed in version [1.2](https://modrinth.com/mod/weather2-additions/version/1.2)!
