### ISSUE TITLE
tablet completely cooked

### ISSUE THREAD

**Issue by Benjino11** [NikoGameing/Weather2-Additions#2]
![2024-11-03_18 06 26](https://github.com/user-attachments/assets/633580ac-d55e-446f-9c86-f7a80af26687)

battery % is over 9000?

and wind speed 300 mph smh

**Comment by Benjino11** [comment]
these are the mods im using

![h23g235f2353h7h4](https://github.com/user-attachments/assets/279ff163-f7dc-4662-9995-29d29bd2477d)

**Comment by NikoGameing** [comment]
i cant reproduce this issue at all, the only suggestions i really have are updating to a [more recent version](https://modrinth.com/mod/weather2-additions/version/1.1) of the mod (version 1.1 as of now) or messing around with shader options or optifine, sorry

**Comment by NikoGameing** [comment]
i'll stick a "more info needed" tag on this if anyone else has this issue

**Comment by Benjino11** [comment]
alr

**Comment by Benjino11** [comment]
its just randomized it shows 4mph then 600mph its just spiking

**Comment by NikoGameing** [comment]
i will say that the mph value is kind of arbitrarily multiplied and squared based off of real-life wind speeds in storms because weather2 doesn't really give you a realistic wind value, it's usually some number between 0-2 if i remember correctly

**Comment by NikoGameing** [comment]
found this issue later down the line, its been fixed in 2.2
